version: '3.9'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8000:80
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    image: php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    tty: true


  mysql:
    container_name: mysql
    image: mysql:8.0.36-debian
    env_file:
      - ./env/mysql.env

  composer:
    container_name: composer
    image: composer
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
   image: node:alpine3.19
   working_dir: /var/www/html
   entrypoint: ["npm"]
   volumes:
     - ./src:/var/www/html